MONPROJ/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vol/', include('reservation.urls')),
    path('compagnie/', include('compagnie.urls')),
    path('trajet/', include('trajet.urls')),
    # path('', views.home,name='base'),
    path('',views.home,name="accueil"),
]

compagnie/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.homecompagnie,name='homecompagnie'),
    path('<int:compagnie_id>', views.detailcompagnie,name='detailcompagnie'),
    path('<int:compagnie_id>/update', views.updatecompagnie,name='updatecompagnie'),
    
]

reservation/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home,name='home'),
    path('<int:vol_id>', views.detail,name='detail'),
    path('<int:vol_d>/listcompagnie', views.listcomp,name='listcomp'),
    path('<int:vol_d>/supvol', views.supvol,name='supvol'),
]

trajet/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.hometrajet,name='hometrajet'),
    path('<int:trajet_id>', views.detailtrajet,name='detailtrajet'),
    
]

compagnie/models.py
from django.db import models

# Create your models here.

reservation/models.py
from django.db import models

# Create your models here.
from django.db import models

class Trajet(models.Model):
    depart = models.CharField(max_length=30)
    arrivee = models.CharField(max_length=30)
    

    def __str__(self):
        return "%s %s" % (self.depart, self.arrivee)

class Vol(models.Model):
    prix= models.FloatField(max_length=100)
    date = models.CharField(max_length=20)
    heure = models.CharField(max_length=15)
    trajet = models.ForeignKey(Trajet, on_delete=models.CASCADE)

    def __str__(self):
        return self.date

    class Meta:
        ordering = ['id']

class Compagnie(models.Model):
    nom = models.CharField(max_length=100)
    logo = models.CharField(max_length=100)
    vols = models.ManyToManyField(Vol)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.nom        

trajet/models.py
from django.db import models

# Create your models here.

reservation/forms.py
from django.core import validators
from django import forms
from reservation.models import Compagnie

class CompagnieRegistration(forms.ModelForm):
    class Meta:
        model=Compagnie
        fields=['nom','logo']

MONPROJ/views.py
from django.shortcuts import render
def home(request):
    return render(request,'accueil.html',locals())

compagnie/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse
from reservation.models import Vol,Compagnie
from reservation.forms import CompagnieRegistration

# Create your views here.

def homecompagnie(request):
    #a="BIENVENUE DANS HOME"
    compagnie=Compagnie.objects.all()
    


    
    
    #a="bonjour"
    #vol=Vol

    #return HttpResponse(compagnie)
    return render(request,'homecompagnie.html',locals())

def detailcompagnie(request,compagnie_id):
    compagnie=Compagnie.objects.get(pk=compagnie_id)
    return render(request,'detailcompagnie.html',locals())

def updatecompagnie(request,compagnie_id):
    if request.method == 'POST':
        compagnie=Compagnie.objects.all()
        compagnies=Compagnie.objects.get(pk=compagnie_id)
        mcompagnie=CompagnieRegistration(request.POST,instance=compagnies)
        # fm=CompagnieRegistration(request.POST)
        if mcompagnie.is_valid():
            mcompagnie.save()
            modificationcomp='Vous avez modifier la compagnie ',compagnie_id,' avec succes'
            
            return render(request,'homecompagnie.html',locals())
    else:
        compagnies=Compagnie.objects.get(pk=compagnie_id)
        mcompagnie=CompagnieRegistration(instance=compagnies)
        # fm=CompagnieRegistration(request.POST)
        
        


    return render(request,'updatecompagnie.html',{'form':mcompagnie})    

reservation/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Vol,Compagnie

# Create your views here.

def home(request):
    #a="BIENVENUE DANS HOME"
    vol=Vol.objects.all()
    compagnie=Compagnie.objects.all()
    
    
    
    #a="bonjour"
    #vol=Vol

    #return HttpResponse(vol)
    return render(request,'home.html',locals())


def listcomp(request,vol_d):
    #a="BIENVENUE DANS HOME"
    #compagnie=Compagnie.objects.all()
    vol=Vol.objects.all()
    volid=Vol.objects.get(id=vol_d).compagnie_set.all()
    lng=len(volid)
    
    #message="{} est à {}.  ,  sa date de depart est le {}.à {} ".format(vol_d,compagnie.nom,compagnie.logo)
    #return HttpResponse(message)
    #a="bonjour"
    #vol=Vol

    #return HttpResponse(volid)
    return render(request,'listcom.html',locals())

def detail(request,vol_id):
    #a="bonjour tu as saisi",compagnie_id
    vol=Vol.objects.get(pk=vol_id)
    #message="Le vol {} est à {}.  ,  sa date de depart est le {}.à {} ".format(vol_id,vol.prix,vol.date,vol.heure)
    return render(request,'detailvol.html',locals())

def supvol(request,vol_d):
    #a="bonjour tu as saisi",compagnie_id
    volsup=Vol.objects.get(pk=vol_d)
    volsup.delete()
    vol=Vol.objects.all()
    compagnie=Compagnie.objects.all()
    message= "vous avez supprimer le vol", vol_d
    return render(request,'home.html',locals())
    
    
    

trajet/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse
from reservation.models import Vol,Trajet

# Create your views here.

def hometrajet(request):
    #a="BIENVENUE DANS HOME"
    trajet=Trajet.objects.all()
    vol=Vol.objects.all()
    


    
    
    #a="bonjour"
    #vol=Vol

    # return HttpResponse(trajet)
    return render(request,'hometrajet.html',locals())

def detailtrajet(request,trajet_id):
    trajet=Trajet.objects.get(pk=trajet_id)
    return render(request,'detailtrajet.html',locals())

compagnie/templates/detailcompagnie.html
{%extends 'accueil.html'%}
{% block contenu %}
{%load static%}

</br>

<h2 > Voici la compagnie {{compagnie.id}} </h2>
</br>
<table border="1" cellpadding="20" class="table table-sm">
    <tr>
        <th>logo</th>
        <th>id</th>
        <th>nom</th>

        
    </tr>


    <tr>
        <td> <img src="{% static compagnie.logo  %} "  alt='Wikihow LOGO' width='200' height='200'/></td>
        <td>{{compagnie.id}} </td> 
        <td>{{compagnie.nom}}</td>
        <td> <a href="{%url 'updatecompagnie' compagnie.id %} "  class="btn btn-primary  bg-dark">modifier</a></td>


   
    </tr>
    
   
</table>
</br>

{% endblock %}

compagnie/templates/homecompagnie.html
{%extends 'accueil.html'%}
{%load static%}
{% block contenu %}
</br>
{%if modificationcomp %}:
  <h2 class="alert alert-info">{{modificationcomp}}</h2>
{% endif%}
<h2> la listing des compagnies est</h2>
</br>
<table cellpadding="20" class="table table-sm">
    <tr>
        <th></th>
        <th>id</th>
        <th>nom</th>

        <th>liste vol</th>
        
        
    </tr>
{%for compagnie in compagnie %}

    <tr>
        <td> <img src="{% static compagnie.logo  %} " width='100',height='100' alt='Wikihow LOGO' /></td>
        <td ><a href="{%url 'detailcompagnie' compagnie.id  %} " class="btn btn-primary bg-dark" >{{compagnie.id}} </a></td> 
        <td >{{compagnie.nom}}</td>
        
        <td>
        {%for i in compagnie.vols.all%}
        <a href="{%url 'detail' i.id  %} " class="btn btn-primary bg-dark" >vol {{i.id}} </a>
        {%endfor%}
    </td>
        <td> <a href="{%url 'updatecompagnie' compagnie.id %} "  class="btn btn-primary  bg-dark">modifier</a></td>
    </tr>
{%endfor%}
   
</table>
</br>
{% endblock %}

compagnie/templates/updatecompagnie.html
{%extends 'accueil.html'%}
{%load static%}
{% block contenu %}
<!-- <h2>Modifier les informations de la compagnie {{compagnie_id}} </h2>
<form action="" method="POST">
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="modifier" >
</form> -->

<div class="row">
    <div class="col-sm-8" offset-2>
        <h4 class="alert alert-info">Modifier les informations d'une compagnie</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-success" value="modifier" >
        </form> 
    </div>
</div>


{% endblock %}

reservation/templates/detailvol.html
{%extends 'accueil.html'%}
{% block contenu %}
</br>

<h2> Voici le vol {{vol.id}} </h2>
</br>
<table border="1" cellpadding="20" class="table table-sm">
    <tr><th>id</th>
        <th>prix</th>
        <th>date</th>
        <th>heure</th>
        <th>trajet</th>
        <th>liste compagnie</th>
        
    </tr>


    <tr>
        <td> <a href="{%url 'detail' vol.id %} " class="btn btn-primary  bg-dark">{{vol.id}}</a></td>
        <td>{{vol.prix}}</td>
        <td>{{vol.date}}</td>
        <td>{{vol.heure}}</td>
        <td>{{vol.trajet}}</td>
        <td>
        {% for vol in vol.compagnie_set.all %}
        
             <a href="{%url 'detailcompagnie' vol.id %} "  class="btn btn-primary  bg-dark">{{vol.nom}}  </a> 
    
    
    {%endfor%}
</td>
<td> <a href="{%url 'supvol' vol.id %} "  class="btn btn-primary  bg-dark">supprimer</a></td>

</br>

{% endblock %}

reservation/templates/home.html
{%extends 'accueil.html'%}
{% block contenu %}
</br>

<h2> la liste  des vols est</h2>
{%if message %}:
  <h2 class="alert alert-danger">{{message}}</h2>
{% endif%}

</br>
<table border="1" cellpadding="20" class="table table-sm">
    <tr><th>id</th>
        <th>prix</th>
        <th>date</th>
        <th>heure</th>
        <th>trajet</th>
        <th>liste compagnie</th>
        
    </tr>
{%for vol in vol %}

    <tr>
        <td> <a href="{%url 'detail' vol.id %} "  class="btn btn-primary  bg-dark">{{vol.id}}</a></td>
        <td>{{vol.prix}}</td>
        <td>{{vol.date}}</td>
        <td>{{vol.heure}}</td>
        <td><a href="{%url 'detailtrajet' vol.id %} "  class="btn btn-primary  bg-dark" >{{vol.trajet}} </br></a></td>
        <td>{% for vol in vol.compagnie_set.all %}
        
            <a href="{%url 'detailcompagnie' vol.id %} "  class="btn btn-primary  bg-dark" >{{vol.nom}} </br> </a> 
        

            {%endfor%}
        </td>
        <td> <a href="{%url 'supvol' vol.id %} "  class="btn btn-primary  bg-dark">supprimer</a></td>
        

    </tr>
    {%endfor%}
</table> 

</br>

{% endblock %}

templates/accueil.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    
    <!-- Vendor CSS Files -->

    <link href=" {% static 'assets/vendor/aos/aos.css ' %} " rel="stylesheet" />
    <link href=" {% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet" />
    <link href=" {% static 'assets/vendor/boxicons/css/boxicons.min.css' %} " rel="stylesheet" />
    <!-- <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'> -->
    <link href=" {% static 'assets/vendor/glightbox/css/glightbox.min.css ' %} " rel="stylesheet" />
    <link href=" {% static 'assets/vendor/swiper/swiper-bundle.min.css' %} " rel="stylesheet" />
    

    

    <!-- Template Main CSS File -->
    <link href=" {% static 'assets/css/style.css' %} " rel="stylesheet" />
    <!-- <link href=" {% static 'css/style.css ' %} " rel="stylesheet" /> -->
</head>
<body>
  <header id="header">
  <nav id="navbar" class="nav-menu navbar">
    <ul>
      <li><a href="{%url 'accueil' %}" class="nav-link scrollto "><i class="bx bx-home-circle"></i> <span>Home</span></a></li>
      <li><a href="{%url 'home' %}" class="nav-link scrollto"><i class="bx bxs-plane-alt"></i> <span>Vol</span></a></li>
      <li><a href="{%url 'homecompagnie' %}" class="nav-link scrollto"><i class="bx bxs-coin-stack"></i> <span>Compagnies</span></a></li>
      <li><a href="{%url 'hometrajet' %}" class="nav-link scrollto"><i class="bx bxs-map"></i> <span>Trajet</span></a></li>
      
    </ul>
  </nav><!-- .nav-menu -->
</header>







<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
  <div class="hero-container">
    
    {% block contenu %}
    <h1>Site de Reservation</h1>
    {% endblock %}
  </div>
</section>




<!-- End Hero -->















  

  <link href=" {% static 'assets/vendor/purecounter/purecounter_vanilla.js ' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/aos/aos.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/glightbox/js/glightbox.min.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/swiper/swiper-bundle.min.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/typed.js/typed.min.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/waypoints/noframework.waypoints.js' %} " rel="stylesheet" />
  <link href=" {% static 'assets/vendor/php-email-form/validate.js' %} " rel="stylesheet" />

  <!-- Template Main JS File -->
  <link href=" {% static 'assets/js/main.js' %} " rel="stylesheet" />
  
  <!-- <link href=" {% static 'css/style.css ' %} " rel="stylesheet" /> -->
</body>
</html>

trajet/templates/detailtrajet.html
{%extends 'accueil.html'%}
{% block contenu %}
</br>

<h2> la liste  des trajets est</h2>
</br>
<table border="1" cellpadding="20" class="table table-sm">
    <tr><th>id</th>
        <th>depart</th>
        <th>destination</th>
       
        
    </tr>

    <tr>
        <td>{{trajet.id}}</td>
        <td>{{trajet.depart}}</td>
        <td>{{trajet.arrivee}}</td>
        
        <!-- <td>{% for vol in vol.compagnie_set.all %}
            <a href="{%url 'detailcompagnie' vol.id %} "  class="btn btn-primary  bg-dark" >{{vol.nom}} </br> </a> 
            {%endfor%}
        </td> -->
        

    </tr>

</table> 

</br>

{% endblock %}

trajet/templates/hometrajet.html
{%extends 'accueil.html'%}
{% block contenu %}
</br>

<h2> la liste  des trajets est</h2>
</br>
<table border="1" cellpadding="20" class="table table-sm">
    <tr><th>id</th>
        <th>depart</th>
        <th>destination</th>
        <th>liste vols</th>
        
       
        
    </tr>
{%for trajet in trajet %}

    <tr>
        <td> <a href="{%url 'detailtrajet' trajet.id %} "  class="btn btn-primary  bg-dark">{{trajet.id}}</a></td>
        <td>{{trajet.depart}}</td>
        <td>{{trajet.arrivee}}</td>
        
        <td>{% for trajet in trajet.vol_set.all %}
            <a href="{%url 'detail' trajet.id %} "  class="btn btn-primary  bg-dark" >vol {{trajet.id}} </br> </a> 
            {%endfor%}
        </td>
        

    </tr>
    {%endfor%}
</table> 

</br>

{% endblock %}